# @name admin_login
POST https://api.flyttman.se/api/admin-login
Content-Type: application/json

{
    "username": "kolawole",
    "password": "securepassword"
}

####

@admin_token = {{admin_login.response.body.token}}


####

GET https://api.flyttman.se/api/admins/logs
Authorization: Bearer {{admin_token}}
