const path = require("path");
const invoiceService = require("./utils/invoiceService");
const emailService = require("./utils/emailService"); // Assuming emailService is initialized and exported
const dotenv = require("dotenv");

// Load environment variables (needed for emailService)
dotenv.config();

const runTest = async () => {
  const dummyInvoiceData = {
    order_id: `TEST-${Date.now()}`, // Use a unique ID each time
    customer_name: "Kolawole Iwalewa",
    customer_email: "kolawoleiwalewa@gmail.com", // Using the email you provided
    ssn: "19900101-1234", // Example SSN
    service_description: "Local Move with Packing & Cleaning",
    from_city: "Stockholm",
    to_city: "Solna",
    move_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // Move in 1 week
    services: [
      {
        description: "Moving Service (4 hours)",
        quantity: 1,
        unit_price: 4000,
      },
      { description: "Packing Materials", quantity: 1, unit_price: 500 },
      {
        description: "Packing Assistance (2 hours)",
        quantity: 1,
        unit_price: 1000,
      },
      { description: "Move-out Cleaning", quantity: 1, unit_price: 1500 },
    ],
    amount: 7000, // Sum of services (4000 + 500 + 1000 + 1500)
    tax_deduction: 3500, // Example 50% RUT on 7000
    initial_payment: 700, // 20% of (7000 - 3500 = 3500)
    remainingPayment: 2800, // 80% of (7000 - 3500 = 3500)
  };

  console.log("Generating invoice with dummy data...");
  console.log("Data:", JSON.stringify(dummyInvoiceData, null, 2));

  try {
    const invoicePath = await invoiceService.generateInvoice(dummyInvoiceData);
    console.log(`✅ Invoice generated successfully: ${invoicePath}`);

    // Send the invoice via email
    console.log(`📧 Sending invoice to ${dummyInvoiceData.customer_email}...`);

    // Ensure emailService is correctly instantiated if it's a class
    const mailer = emailService.sendEmail ? emailService : new emailService();

    await mailer.sendEmail(
      dummyInvoiceData.customer_email,
      {
        subject: `Test Invoice Generated: ${dummyInvoiceData.order_id}`,
        html: `<p>Hello,</p><p>Please find the test invoice attached (Order ID: ${dummyInvoiceData.order_id}).</p><p>This was generated by the test script.</p>`,
        // Note: The 'template' parameter in sendEmail seems to expect specific template names based on emailService.js
        // Sending raw subject/html might require adjustments to sendEmail or use a generic template if available.
        // For now, assuming sendEmail can handle direct subject/html.
      },
      [
        {
          filename: path.basename(invoicePath),
          path: invoicePath,
          contentType: "application/pdf",
        },
      ]
    );

    console.log(
      `✅ Invoice sent successfully to ${dummyInvoiceData.customer_email}`
    );
  } catch (error) {
    console.error("❌ Error generating or sending invoice:", error);
  }
};

runTest();
